.TH TV 1
.SH NAME
tv \- display whats on tv
.SH SYNOPSIS
.B tv
[
.I options
]
.SH DESCRIPTION
.B tv
is a commandline tool for showing whats on tv. tv uses the XmlTV format for parsing
and requires an url for the channel database. tv support both commandline option or using a config file
.PP
tv will display all selected channels or if no channels are selected, all channels form the channels db.
.SH OPTIONS
.TP
.B -u url 
Path to the channels db file.
.TP
.B -w min-width
Minimum length of a program name.
.TP
.B -t relative time
Set the day in relative, -1 for yesterday and 1 for tomorrow (default: today).
.TP
.B -c [channels]
Channels to list, an empty list equals all channels (default: all channels).
.SH CONFIG SYNTAX
url = string
.br
channels = [strings] 
.br
min-width = int
.br
show-trailing = bool
.br
sort-channels = bool
.br
show-aired = bool

.SH AUTHOR
Per Odlund
.SH SOURCE
https://github.com/dagle/hs-xmltv
